### ISSUE TITLE
Problem running local demo

### ISSUE THREAD

**Issue by sksizer** [gritzko/todomvc-swarm#26]
I cloned the demo app and followed instructions to run test - and get the following error:

```
Swarm server started port 8000
method execution failed { value: '/TodoItem#1om4k02+swarm~nodejs!1om7905+swarm~nodejs.on',
  index: 0 } init TypeError: Cannot call method 'forEach' of undefined
    at SomeSyncable.Swarm.Vector.extend.stats (/Users/me/workspace/learning/todomvc-swarm/model/TodoList.js:47:22)
    at React.createClass.render (/Users/me/workspace/learning/todomvc-swarm/view/MainSection.jsx:36:30)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactCompositeComponent.js:1249:34)
    at null._renderValidatedComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactPerf.js:57:21)
    at ReactCompositeComponentMixin.mountComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactCompositeComponent.js:779:14)
    at null.mountComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactPerf.js:57:21)
    at ReactMultiChild.Mixin.mountChildren (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactMultiChild.js:202:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactDOMComponent.js:198:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactDOMComponent.js:120:14)
    at null.mountComponent (/Users/me/workspace/learning/todomvc-swarm/node_modules/react/lib/ReactPerf.js:57:21)
Cannot call method 'off' of undefined TypeError: Cannot call method 'off' of undefined
    at onceWrap (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:915:18)
    at fail (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:354:17)
    at SomeSyncable.Syncable.extend.deliver (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:408:20)
    at Object._lstn.push.deliver (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:628:30)
    at SomeSyncable.Syncable.extend.emit (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:434:31)
    at SomeSyncable.Syncable.extend.deliver (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Syncable.js:403:22)
    at sendResponse (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Storage.js:84:17)
    at /Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/Storage.js:93:13
    at onRead (/Users/me/workspace/learning/todomvc-swarm/node_modules/swarm/lib/FileStorage.js:83:9)
    at fs.js:271:14
```

**Comment by shanesizer-wf** [comment]
Thanks!
